import type { TemplateConfig } from "./types";

const coaching: TemplateConfig = {
  category: "coaching",
  displayName: "Coaching / Tuition Centre",
  icon: "GraduationCap",
  description: "Fee receipts for tuition centres, coaching classes & academies",
  documentTitle: "Fee Receipt",
  senderLabel: "Institute",
  receiverLabel: "Student",
  color: "text-violet-600",
  accentBg: "bg-violet-50 border-violet-200",
  senderFields: [
    { key: "name", label: "Institute Name", type: "text", span: "full" },
    { key: "address", label: "Address", type: "textarea", span: "full" },
    { key: "contact", label: "Contact Number", type: "tel", span: "half" },
    { key: "email", label: "Email", type: "email", span: "half" },
    { key: "gstin", label: "GSTIN", type: "text", optional: true, span: "half" },
    { key: "regNumber", label: "Registration Number", type: "text", optional: true, span: "half" },
  ],
  receiverFields: [
    { key: "studentName", label: "Student Name", type: "text", span: "half" },
    { key: "guardianName", label: "Father's / Guardian's Name", type: "text", span: "half" },
    { key: "class", label: "Class / Standard", type: "text", span: "half" },
    { key: "batch", label: "Batch / Timing", type: "text", span: "half" },
    { key: "rollNumber", label: "Roll Number", type: "text", optional: true, span: "half" },
    { key: "contact", label: "Contact Number", type: "tel", span: "half" },
  ],
  lineItemColumns: [
    { key: "description", label: "Description", type: "text", width: 55, placeholder: "e.g. Tuition Fee — April" },
    { key: "period", label: "Period / Month", type: "text", width: 25, placeholder: "e.g. April 2024" },
    { key: "amount", label: "Amount (₹)", type: "number", width: 20, prefix: "₹" },
  ],
  lineItemCompute: "direct",
  extraFields: [
    { key: "receiptNumber", label: "Receipt Number", type: "text", span: "half", placeholder: "RCP-001" },
    { key: "paymentDate", label: "Payment Date", type: "date", span: "half" },
    { key: "paymentMode", label: "Payment Mode", type: "select", options: ["Cash", "UPI", "Bank Transfer", "Cheque"], span: "half" },
    { key: "chequeUtr", label: "Cheque / UTR Number", type: "text", span: "half", optional: true, conditional: { field: "paymentMode", value: "Cheque" } },
    { key: "academicYear", label: "Academic Year", type: "text", span: "half", placeholder: "2024-25" },
    { key: "course", label: "Course / Subject", type: "text", span: "half" },
    { key: "nextDueDate", label: "Next Due Date", type: "date", span: "half", optional: true },
    { key: "outstandingBalance", label: "Outstanding Balance (₹)", type: "number", span: "half", optional: true },
  ],
  taxes: [
    { key: "gst18", label: "GST @ 18%", rate: 18, enabled: false, toggleable: true, note: "For commercial coaching not under exemption", group: "gst" },
  ],
  notes: "This is a computer-generated receipt. Please retain for your records.",
  showAmountInWords: true,
  showSignatureBlock: true,
};

const retail: TemplateConfig = {
  category: "retail",
  displayName: "Retail / General Store",
  icon: "ShoppingCart",
  description: "GST tax invoices for shops, supermarkets & general stores",
  documentTitle: "Tax Invoice",
  senderLabel: "Shop / Business",
  receiverLabel: "Customer",
  color: "text-emerald-600",
  accentBg: "bg-emerald-50 border-emerald-200",
  senderFields: [
    { key: "name", label: "Shop / Business Name", type: "text", span: "full" },
    { key: "address", label: "Address", type: "textarea", span: "full" },
    { key: "gstin", label: "GSTIN", type: "text", span: "half" },
    { key: "state", label: "State", type: "text", span: "half" },
    { key: "contact", label: "Contact", type: "tel", span: "half" },
    { key: "email", label: "Email", type: "email", span: "half" },
  ],
  receiverFields: [
    { key: "name", label: "Customer Name", type: "text", span: "half" },
    { key: "address", label: "Address", type: "textarea", optional: true, span: "full" },
    { key: "gstin", label: "GSTIN (B2B)", type: "text", optional: true, span: "half" },
    { key: "phone", label: "Phone", type: "tel", span: "half" },
  ],
  lineItemColumns: [
    { key: "description", label: "Item Description", type: "text", width: 28 },
    { key: "hsn", label: "HSN", type: "text", width: 8 },
    { key: "qty", label: "Qty", type: "number", width: 7 },
    { key: "unit", label: "Unit", type: "text", width: 7, placeholder: "pcs" },
    { key: "rate", label: "Rate (₹)", type: "number", width: 10, prefix: "₹" },
    { key: "discountPct", label: "Disc%", type: "number", width: 7 },
    { key: "gstRate", label: "GST%", type: "number", width: 7, placeholder: "18" },
    { key: "amount", label: "Amount", type: "number", width: 12, computed: true, prefix: "₹" },
  ],
  lineItemCompute: "qty*rate*(1-discPct/100)",
  extraFields: [
    { key: "invoiceNumber", label: "Invoice Number", type: "text", span: "half", placeholder: "INV-001" },
    { key: "invoiceDate", label: "Invoice Date", type: "date", span: "half" },
    { key: "poNumber", label: "PO Number", type: "text", span: "half", optional: true },
    { key: "paymentMode", label: "Payment Mode", type: "select", options: ["Cash", "UPI", "Card", "Bank Transfer", "Credit"], span: "half" },
    { key: "salesperson", label: "Salesperson", type: "text", span: "half", optional: true },
  ],
  taxes: [
    { key: "cgst", label: "CGST", rate: 0, enabled: true, toggleable: false, group: "cgst-sgst", note: "Per item rate / 2" },
    { key: "sgst", label: "SGST", rate: 0, enabled: true, toggleable: false, group: "cgst-sgst", note: "Per item rate / 2" },
    { key: "igst", label: "IGST", rate: 0, enabled: false, toggleable: true, group: "igst", note: "Inter-state: toggle to IGST" },
  ],
  notes: "Goods once sold will not be taken back. E&OE.",
  showAmountInWords: true,
  showSignatureBlock: false,
};

const restaurant: TemplateConfig = {
  category: "restaurant",
  displayName: "Restaurant / Café",
  icon: "UtensilsCrossed",
  description: "KOT bills and dine-in/takeaway invoices with GST & service charge",
  documentTitle: "Bill",
  senderLabel: "Restaurant",
  receiverLabel: "Guest",
  color: "text-orange-600",
  accentBg: "bg-orange-50 border-orange-200",
  senderFields: [
    { key: "name", label: "Restaurant Name", type: "text", span: "full" },
    { key: "address", label: "Address", type: "textarea", span: "full" },
    { key: "fssai", label: "FSSAI Number", type: "text", span: "half" },
    { key: "gstin", label: "GSTIN", type: "text", span: "half" },
    { key: "contact", label: "Contact", type: "tel", span: "half" },
    { key: "tableNumber", label: "Table Number", type: "text", span: "half" },
  ],
  receiverFields: [
    { key: "guestName", label: "Guest / Customer Name", type: "text", optional: true, span: "half" },
    { key: "tableNo", label: "Table No.", type: "text", span: "half" },
    { key: "covers", label: "Cover Count (Guests)", type: "number", span: "half" },
    { key: "waiter", label: "Waiter / Server", type: "text", optional: true, span: "half" },
    { key: "orderType", label: "Order Type", type: "select", options: ["Dine-in", "Takeaway", "Delivery"], span: "half" },
    { key: "deliveryAddress", label: "Delivery Address", type: "textarea", optional: true, conditional: { field: "orderType", value: "Delivery" }, span: "full" },
  ],
  lineItemColumns: [
    { key: "description", label: "Item Name", type: "text", width: 38 },
    { key: "category", label: "Category", type: "select", options: ["Food", "Beverages", "Desserts", "Starters", "Main Course"], width: 18 },
    { key: "qty", label: "Qty", type: "number", width: 8 },
    { key: "rate", label: "Rate (₹)", type: "number", width: 12, prefix: "₹" },
    { key: "amount", label: "Amount", type: "number", width: 14, computed: true, prefix: "₹" },
  ],
  lineItemCompute: "qty*rate",
  extraFields: [
    { key: "billNumber", label: "Bill Number", type: "text", span: "half", placeholder: "BILL-001" },
    { key: "dateTime", label: "Date & Time", type: "text", span: "half" },
    { key: "kotNumber", label: "KOT Number", type: "text", span: "half", optional: true },
  ],
  taxes: [
    { key: "cgst2_5", label: "CGST @ 2.5%", rate: 2.5, enabled: true, toggleable: false, group: "5pct" },
    { key: "sgst2_5", label: "SGST @ 2.5%", rate: 2.5, enabled: true, toggleable: false, group: "5pct" },
    { key: "cgst6", label: "CGST @ 6%", rate: 6, enabled: false, toggleable: true, group: "12pct", note: "For AC restaurants (12% slab)" },
    { key: "sgst6", label: "SGST @ 6%", rate: 6, enabled: false, toggleable: true, group: "12pct" },
    { key: "serviceCharge", label: "Service Charge @ 10%", rate: 10, enabled: false, toggleable: true, note: "Voluntary — at customer's discretion" },
  ],
  notes: "Service charge is voluntary and at the customer's discretion as per Indian law. Thank you for dining with us!",
  showAmountInWords: false,
  showSignatureBlock: false,
};

const medical: TemplateConfig = {
  category: "medical",
  displayName: "Medical / Clinic / Pharmacy",
  icon: "Stethoscope",
  description: "Medical bills, clinic invoices & pharmacy receipts with GST",
  documentTitle: "Medical Bill",
  senderLabel: "Hospital / Clinic",
  receiverLabel: "Patient",
  color: "text-red-600",
  accentBg: "bg-red-50 border-red-200",
  senderFields: [
    { key: "name", label: "Hospital / Clinic / Pharmacy Name", type: "text", span: "full" },
    { key: "regNumber", label: "Registration Number (MCI / State)", type: "text", span: "half" },
    { key: "address", label: "Address", type: "textarea", span: "full" },
    { key: "contact", label: "Contact", type: "tel", span: "half" },
    { key: "doctorName", label: "Doctor Name", type: "text", span: "half", optional: true },
    { key: "gstin", label: "GSTIN", type: "text", optional: true, span: "half" },
  ],
  receiverFields: [
    { key: "patientName", label: "Patient Name", type: "text", span: "half" },
    { key: "age", label: "Age", type: "number", span: "half" },
    { key: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Other"], span: "half" },
    { key: "patientId", label: "Patient ID / UHID", type: "text", optional: true, span: "half" },
    { key: "referredBy", label: "Referred By", type: "text", optional: true, span: "half" },
    { key: "contact", label: "Contact", type: "tel", span: "half" },
    { key: "address", label: "Address", type: "textarea", optional: true, span: "full" },
  ],
  lineItemColumns: [
    { key: "description", label: "Service / Medicine", type: "text", width: 30 },
    { key: "hsnSac", label: "HSN/SAC", type: "text", width: 10, optional: true },
    { key: "batch", label: "Batch No.", type: "text", width: 10, optional: true },
    { key: "expiry", label: "Expiry", type: "text", width: 10, optional: true },
    { key: "qty", label: "Qty", type: "number", width: 7 },
    { key: "unit", label: "Unit", type: "text", width: 8, placeholder: "Tab" },
    { key: "rate", label: "Rate (₹)", type: "number", width: 10, prefix: "₹" },
    { key: "discount", label: "Disc (₹)", type: "number", width: 7 },
    { key: "amount", label: "Amount", type: "number", width: 10, computed: true, prefix: "₹" },
  ],
  lineItemCompute: "qty*rate-disc",
  extraFields: [
    { key: "billNumber", label: "Bill Number", type: "text", span: "half", placeholder: "MED-001" },
    { key: "billDate", label: "Bill Date", type: "date", span: "half" },
    { key: "consultationDate", label: "Consultation Date", type: "date", span: "half", optional: true },
    { key: "diagnosis", label: "Diagnosis", type: "textarea", span: "full", optional: true },
    { key: "doctorName", label: "Doctor's Name", type: "text", span: "half" },
    { key: "paymentMode", label: "Payment Mode", type: "select", options: ["Cash", "UPI", "Card", "Insurance", "Bank Transfer"], span: "half" },
    { key: "insurance", label: "Insurance Details", type: "text", span: "full", optional: true },
  ],
  taxes: [
    { key: "gst5", label: "GST @ 5%", rate: 5, enabled: false, toggleable: true, group: "pharmacy", note: "For medicines" },
    { key: "gst12", label: "GST @ 12%", rate: 12, enabled: false, toggleable: true, group: "pharmacy" },
    { key: "gst18", label: "GST @ 18%", rate: 18, enabled: false, toggleable: true, group: "services", note: "For non-exempt services" },
  ],
  notes: "Medical services are largely GST-exempt. Please verify applicability with your tax advisor.",
  showAmountInWords: true,
  showSignatureBlock: true,
};

const freelance: TemplateConfig = {
  category: "freelance",
  displayName: "Freelance / Consulting",
  icon: "Briefcase",
  description: "Professional invoices for freelancers, consultants & agencies",
  documentTitle: "Invoice",
  senderLabel: "Freelancer / Company",
  receiverLabel: "Client",
  color: "text-blue-600",
  accentBg: "bg-blue-50 border-blue-200",
  senderFields: [
    { key: "name", label: "Your Name / Company", type: "text", span: "full" },
    { key: "address", label: "Address", type: "textarea", span: "full" },
    { key: "email", label: "Email", type: "email", span: "half" },
    { key: "phone", label: "Phone", type: "tel", span: "half" },
    { key: "website", label: "Website", type: "text", optional: true, span: "half" },
    { key: "pan", label: "PAN", type: "text", span: "half" },
    { key: "gstin", label: "GSTIN", type: "text", optional: true, span: "half" },
    { key: "bankName", label: "Bank Name", type: "text", span: "half" },
    { key: "accountNo", label: "Account Number", type: "text", span: "half" },
    { key: "ifsc", label: "IFSC Code", type: "text", span: "half" },
  ],
  receiverFields: [
    { key: "clientName", label: "Client Name", type: "text", span: "half" },
    { key: "company", label: "Company Name", type: "text", optional: true, span: "half" },
    { key: "address", label: "Address", type: "textarea", span: "full" },
    { key: "gstin", label: "GSTIN", type: "text", optional: true, span: "half" },
    { key: "email", label: "Email", type: "email", span: "half" },
    { key: "phone", label: "Phone", type: "tel", span: "half" },
    { key: "projectRef", label: "Project / PO Reference", type: "text", span: "half" },
  ],
  lineItemColumns: [
    { key: "description", label: "Description of Service", type: "text", width: 35, placeholder: "e.g. Website Design" },
    { key: "sacCode", label: "SAC", type: "text", width: 8, optional: true },
    { key: "period", label: "Period / Hours", type: "text", width: 15, placeholder: "e.g. April 2024" },
    { key: "qty", label: "Qty / Hrs", type: "number", width: 8 },
    { key: "rate", label: "Rate (₹)", type: "number", width: 14, prefix: "₹" },
    { key: "amount", label: "Amount", type: "number", width: 14, computed: true, prefix: "₹" },
  ],
  lineItemCompute: "qty*rate",
  extraFields: [
    { key: "invoiceNumber", label: "Invoice Number", type: "text", span: "half", placeholder: "INV-001" },
    { key: "invoiceDate", label: "Invoice Date", type: "date", span: "half" },
    { key: "dueDate", label: "Due Date", type: "date", span: "half" },
    { key: "paymentTerms", label: "Payment Terms", type: "select", options: ["Due on Receipt", "Net 15", "Net 30", "Net 45"], span: "half" },
    { key: "currency", label: "Currency", type: "select", options: ["INR (₹)", "USD ($)", "EUR (€)"], span: "half" },
    { key: "tds", label: "TDS Deduction %", type: "number", span: "half", optional: true, placeholder: "10" },
  ],
  taxes: [
    { key: "cgst9", label: "CGST @ 9%", rate: 9, enabled: true, toggleable: false, group: "cgst-sgst" },
    { key: "sgst9", label: "SGST @ 9%", rate: 9, enabled: true, toggleable: false, group: "cgst-sgst" },
    { key: "igst18", label: "IGST @ 18%", rate: 18, enabled: false, toggleable: true, group: "igst", note: "Inter-state: use instead of CGST+SGST" },
    { key: "tdsDeduction", label: "Less: TDS @ 10%", rate: 10, enabled: false, toggleable: true, isDeduction: true, note: "TDS deducted by client" },
  ],
  notes: "Payment due as per terms above. A late payment fee of 2% per month may be charged on overdue amounts.",
  showAmountInWords: true,
  showSignatureBlock: true,
};

const construction: TemplateConfig = {
  category: "construction",
  displayName: "Construction / Contractor",
  icon: "HardHat",
  description: "Running account bills & work contract invoices for contractors",
  documentTitle: "Tax Invoice / RA Bill",
  senderLabel: "Contractor / Firm",
  receiverLabel: "Client / Owner",
  color: "text-yellow-700",
  accentBg: "bg-yellow-50 border-yellow-200",
  senderFields: [
    { key: "name", label: "Contractor / Firm Name", type: "text", span: "full" },
    { key: "address", label: "Address", type: "textarea", span: "full" },
    { key: "gstin", label: "GSTIN", type: "text", span: "half" },
    { key: "pan", label: "PAN", type: "text", span: "half" },
    { key: "licenseNo", label: "Contractor License No.", type: "text", optional: true, span: "half" },
    { key: "contact", label: "Contact", type: "tel", span: "half" },
    { key: "email", label: "Email", type: "email", span: "half" },
  ],
  receiverFields: [
    { key: "clientName", label: "Client / Owner Name", type: "text", span: "half" },
    { key: "projectName", label: "Project Name", type: "text", span: "half" },
    { key: "siteAddress", label: "Site Address", type: "textarea", span: "full" },
    { key: "contact", label: "Contact", type: "tel", span: "half" },
  ],
  lineItemColumns: [
    { key: "description", label: "Work Description / Item", type: "text", width: 35, placeholder: "e.g. Brick Masonry" },
    { key: "unit", label: "Unit", type: "text", width: 10, placeholder: "sqft" },
    { key: "qty", label: "Qty", type: "number", width: 10 },
    { key: "rate", label: "Rate (₹)", type: "number", width: 15, prefix: "₹" },
    { key: "amount", label: "Amount", type: "number", width: 15, computed: true, prefix: "₹" },
    { key: "remarks", label: "Remarks", type: "text", width: 15, optional: true },
  ],
  lineItemCompute: "qty*rate",
  extraFields: [
    { key: "raBillNumber", label: "RA Bill Number", type: "text", span: "half", placeholder: "RAB-001" },
    { key: "billDate", label: "Bill Date", type: "date", span: "half" },
    { key: "workOrderNumber", label: "Work Order Number", type: "text", span: "half" },
    { key: "workOrderDate", label: "Work Order Date", type: "date", span: "half" },
    { key: "billPeriodFrom", label: "Bill Period From", type: "date", span: "half" },
    { key: "billPeriodTo", label: "Bill Period To", type: "date", span: "half" },
    { key: "previousBillsPaid", label: "Less: Previous Bills Paid (₹)", type: "number", span: "half", optional: true },
    { key: "securityDeposit", label: "Security Deposit %", type: "number", span: "half", optional: true },
    { key: "labourCess", label: "Labour Cess @ 1%", type: "number", span: "half", optional: true },
    { key: "tdsPct", label: "TDS %", type: "number", span: "half", optional: true },
  ],
  taxes: [
    { key: "cgst9", label: "CGST @ 9%", rate: 9, enabled: true, toggleable: false, group: "18pct" },
    { key: "sgst9", label: "SGST @ 9%", rate: 9, enabled: true, toggleable: false, group: "18pct" },
    { key: "cgst6", label: "CGST @ 6%", rate: 6, enabled: false, toggleable: true, group: "12pct", note: "12% slab for affordable housing / Govt contracts" },
    { key: "sgst6", label: "SGST @ 6%", rate: 6, enabled: false, toggleable: true, group: "12pct" },
  ],
  notes: "Payment within 30 days of bill submission. Interest @ 18% p.a. on delayed payments.",
  showAmountInWords: true,
  showSignatureBlock: true,
};

const transport: TemplateConfig = {
  category: "transport",
  displayName: "Transport / Logistics",
  icon: "Truck",
  description: "Freight invoices, lorry receipts & logistics billing with GST",
  documentTitle: "Freight Invoice",
  senderLabel: "Transport Company",
  receiverLabel: "Consignor / Consignee",
  color: "text-cyan-700",
  accentBg: "bg-cyan-50 border-cyan-200",
  senderFields: [
    { key: "name", label: "Transport Company Name", type: "text", span: "full" },
    { key: "address", label: "Address", type: "textarea", span: "full" },
    { key: "gstin", label: "GSTIN", type: "text", span: "half" },
    { key: "pan", label: "PAN", type: "text", span: "half" },
    { key: "contact", label: "Contact", type: "tel", span: "half" },
    { key: "vehicleNo", label: "Vehicle Number", type: "text", optional: true, span: "half" },
  ],
  receiverFields: [
    { key: "consignorName", label: "Consignor Name", type: "text", span: "half" },
    { key: "consignorAddress", label: "Consignor Address", type: "textarea", span: "full" },
    { key: "consigneeName", label: "Consignee Name", type: "text", span: "half" },
    { key: "consigneeAddress", label: "Consignee Address", type: "textarea", span: "full" },
    { key: "deliveryContact", label: "Delivery Contact", type: "tel", span: "half" },
  ],
  lineItemColumns: [
    { key: "description", label: "Description of Goods", type: "text", width: 25 },
    { key: "from", label: "From (Origin)", type: "text", width: 15 },
    { key: "to", label: "To (Destination)", type: "text", width: 15 },
    { key: "weight", label: "Weight / Vol.", type: "text", width: 10 },
    { key: "packages", label: "Packages", type: "number", width: 8 },
    { key: "rate", label: "Freight Rate (₹)", type: "number", width: 13, prefix: "₹" },
    { key: "amount", label: "Amount", type: "number", width: 12, computed: true, prefix: "₹" },
  ],
  lineItemCompute: "direct",
  extraFields: [
    { key: "lrNumber", label: "LR / Docket Number", type: "text", span: "half", placeholder: "LR-001" },
    { key: "invoiceDate", label: "Invoice Date", type: "date", span: "half" },
    { key: "vehicleNumber", label: "Vehicle Number", type: "text", span: "half" },
    { key: "driverName", label: "Driver Name", type: "text", span: "half", optional: true },
    { key: "distance", label: "Distance (km)", type: "number", span: "half", optional: true },
    { key: "deliveryDate", label: "Expected Delivery Date", type: "date", span: "half" },
    { key: "mode", label: "Mode", type: "select", options: ["Road", "Rail", "Air", "Sea"], span: "half" },
    { key: "fuelSurcharge", label: "Fuel Surcharge (₹)", type: "number", span: "half", optional: true },
    { key: "detention", label: "Detention / Demurrage (₹)", type: "number", span: "half", optional: true },
  ],
  taxes: [
    { key: "gst5", label: "GST @ 5% (GTA — RCM)", rate: 5, enabled: true, toggleable: true, note: "GST payable under Reverse Charge by recipient" },
    { key: "gst12", label: "GST @ 12% (with ITC)", rate: 12, enabled: false, toggleable: true, note: "Transport with input tax credit" },
  ],
  notes: "GST is payable under Reverse Charge Mechanism by the recipient of the transport service.",
  showAmountInWords: true,
  showSignatureBlock: true,
};

const salon: TemplateConfig = {
  category: "salon",
  displayName: "Salon / Spa / Beauty",
  icon: "Scissors",
  description: "Service bills for salons, spas & beauty parlours with GST",
  documentTitle: "Bill",
  senderLabel: "Salon / Spa",
  receiverLabel: "Customer",
  color: "text-pink-600",
  accentBg: "bg-pink-50 border-pink-200",
  senderFields: [
    { key: "name", label: "Salon / Spa Name", type: "text", span: "full" },
    { key: "address", label: "Address", type: "textarea", span: "full" },
    { key: "contact", label: "Contact", type: "tel", span: "half" },
    { key: "email", label: "Email", type: "email", optional: true, span: "half" },
    { key: "gstin", label: "GSTIN", type: "text", optional: true, span: "half" },
  ],
  receiverFields: [
    { key: "customerName", label: "Customer Name", type: "text", span: "half" },
    { key: "contact", label: "Contact", type: "tel", optional: true, span: "half" },
    { key: "membershipId", label: "Membership ID", type: "text", optional: true, span: "half" },
    { key: "stylist", label: "Stylist / Therapist", type: "text", optional: true, span: "half" },
  ],
  lineItemColumns: [
    { key: "description", label: "Service Description", type: "text", width: 30, placeholder: "e.g. Haircut & Style" },
    { key: "duration", label: "Duration", type: "text", width: 12, optional: true, placeholder: "45 min" },
    { key: "stylist", label: "Stylist", type: "text", width: 15 },
    { key: "qty", label: "Qty", type: "number", width: 7 },
    { key: "rate", label: "Rate (₹)", type: "number", width: 12, prefix: "₹" },
    { key: "discountPct", label: "Disc%", type: "number", width: 8 },
    { key: "amount", label: "Amount", type: "number", width: 14, computed: true, prefix: "₹" },
  ],
  lineItemCompute: "qty*rate*(1-discPct/100)",
  extraFields: [
    { key: "billNumber", label: "Bill Number", type: "text", span: "half", placeholder: "BILL-001" },
    { key: "dateTime", label: "Date & Time", type: "text", span: "half" },
    { key: "paymentMode", label: "Payment Mode", type: "select", options: ["Cash", "UPI", "Card", "Wallet"], span: "half" },
    { key: "tipAmount", label: "Tip Amount (₹)", type: "number", span: "half", optional: true },
    { key: "loyaltyPoints", label: "Loyalty Points Earned", type: "number", span: "half", optional: true },
  ],
  taxes: [
    { key: "cgst9", label: "CGST @ 9%", rate: 9, enabled: true, toggleable: false, group: "services" },
    { key: "sgst9", label: "SGST @ 9%", rate: 9, enabled: true, toggleable: false, group: "services" },
    { key: "productGst12", label: "Product GST @ 12%", rate: 12, enabled: false, toggleable: true, group: "products", note: "For retail products sold" },
  ],
  notes: "Thank you for visiting! Tips are at your discretion and appreciated.",
  showAmountInWords: false,
  showSignatureBlock: false,
};

export const TEMPLATE_CONFIGS: Record<string, TemplateConfig> = {
  coaching,
  retail,
  restaurant,
  medical,
  freelance,
  construction,
  transport,
  salon,
};

export const ALL_CATEGORIES = [
  coaching,
  retail,
  restaurant,
  medical,
  freelance,
  construction,
  transport,
  salon,
];

export function getTemplateConfig(category: string): TemplateConfig {
  const config = TEMPLATE_CONFIGS[category];
  if (!config) throw new Error(`Unknown template category: ${category}`);
  return config;
}
